[[constraint]]
  name = "github.com/mmcdole/gofeed"
  version = "1.0.0-beta2"

[[constraint]]
  name = "gopkg.in/mailgun/mailgun-go.v1"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"
